---

- hosts: all
  become: yes
  tasks:
    - name: Installation des packages git make & go
      ansible.builtin.package:
        name: 
          - git
          - make
          - go
        state: latest 

    - name: pull du repo golang 
      git:
        repo: https://github.com/BastienBalaud/golang-myip.git
        dest: /opt/golang-myip

    - name: Modification pour écouter sur le port 80
      ansible.builtin.replace:
        path: /opt/golang-myip/server.go
        regexp: '8080'
        replace: '80'      
   
    - name: Make golang-myip
      ansible.builtin.shell: cd /opt/golang-myip/ && make
  
    - name: Creation du ficher golang-myip.service 
      file:
        path: /tmp/golang-myip.service
        state: touch          
        mode: 0777


    - name: Ajout du contenu du service
      shell: |
       echo "[Unit]
       Description=Service systeme Golang-MyIP
       
       #Ciblage du service reseau
       After=network.target
       
       [Service]
       #Selection du repertoire d'execution du fichier
       WorkingDirectory=/opt/golang-myip/
       ExecStart=/opt/golang-myip/build/server.x86_64
       
       [Install]
       #Installation pour tout les utilisateurs
       WantedBy=multi-user.target" >> /tmp/golang-myip.service

  
    - name: copie du service golang-myip
      ansible.builtin.shell: mv /tmp/golang-myip.service /etc/systemd/system/golang-myip.service
      
    - name: autorisatisation SElinux pour le service
      ansible.builtin.shell: setenforce 0
      # desactivation temporaire du module de securite linux pour eviter des problemes

    - name: reload du daemon systemd
      ansible.builtin.shell: systemctl daemon-reload

    - name: enable du service golang-myip
      ansible.builtin.systemd:
        name: golang-myip
        enabled: yes

    - name: demarrage du service golang-myip
      ansible.builtin.systemd:
        name: golang-myip
        state: started

    - name: Mode permissive pour SELinux permanent pour utiliser le service golang-myip
      ansible.posix.selinux:
        policy: targeted
        state: permissive   
        
    - name: Ajout cles publiques pour Bastien Balaud
      authorized_key:
        user: root
        state: present
        key: https://github.com/BastienBalaud.keys

    - name: Observabilitée de l'état de la VM
      ansible.builtin.debug:
        var: ansible_facts
