---

- hosts: all
  become: yes
  tasks:
    - name: Installation des packages git make & go
      ansible.builtin.package:
        name: 
          - git
          - make
          - go
        state: latest 

    - name: pull du repo golang 
      git:
        repo: https://github.com/BastienBalaud/golang-myip.git
        dest: /opt/golang-myip
   
    - name: make golang-myip
      ansible.builtin.shell: cd /opt/golang-myip/ && make
  
    - name: copie du service golang-myip
      ansible.builtin.copy:
        src: /opt/golang-myip/golang-myip.service
        dest: /etc/systemd/system/golang-myip.service

    - name: reload du daemon systemd
      ansible.builtin.systemd:
        deamon_reload: yes

    - name: enable du service golang-myip
      ansible.builtin.systemd:
        name: golang-myip
        enabled: yes

    - name: demarrage du service golang-myip
      ansible.builtin.systemd:
        name: golang-myip
        state: started
   
        
